language: node_js
deploy:
  provider: releases
  api_key: 
    secure: ZmKWyBKF7DQQLyM9arptGuqr5osjKttOVOIIi4ra+Nvgea7k3H0GXgqlQXIuHRYgr25XWKMlnVfUn2GSrFLr3M0OqZ9odZ8wcaSidU9r3Ty1qrPOrmrqXVk+BUN4BckpfqI+NPJlgLq5zJT5216JYU40ozXpIo5VnCxzGFU0GWbzQud9ZBhVvw4xFwH9S7Vecu9lJcIT3Eb5YkkRZ0LLS6D0WCyzMs2cYcqN5xl26loO2G7Ix6JD3+RCLYES27lgiVWs71RVHhOWJeSU0w4CxR514GFyO/j3+LXgtwprvpb3YuyJN6N3ybdqZhAx7TjExKTa1uLnIC5rPeE9bk3F2jDIzOQjFugi+RaIJLTwoot80v20AxOxnjBtjOJCzb7DjNkjRzk0RO4NTvrh7h894nrjGrqqvWzLAJ03AZfC2IzkhGWyi+4hdjI9xIlmrkT6oyuH0uB89pOy75pYTUhLsRCHf8zMKeu05K6dR0WxIwIdXsK8IY9d0y1SE6qncq3hE7DSnyebRBmL4e2Bh0QVvLTCJ7dv8o4wUMJ+6E+KgQR3Maw5lWbJywU1kB0XUhNCRpZmkBIxAOQ/1eCOOmZHL+BXicualinaUG6OZl2Ye6nhnsMQhqylhAT87kihqZGlg744QGKMZ+0dJ2JPP+JS7rF6+q11pRbaNavhceJ65gk=
  file: vault/**/*
  on:
    tags: true
  skip_cleanup: 'true'
env:
  global:
    secure: ZmKWyBKF7DQQLyM9arptGuqr5osjKttOVOIIi4ra+Nvgea7k3H0GXgqlQXIuHRYgr25XWKMlnVfUn2GSrFLr3M0OqZ9odZ8wcaSidU9r3Ty1qrPOrmrqXVk+BUN4BckpfqI+NPJlgLq5zJT5216JYU40ozXpIo5VnCxzGFU0GWbzQud9ZBhVvw4xFwH9S7Vecu9lJcIT3Eb5YkkRZ0LLS6D0WCyzMs2cYcqN5xl26loO2G7Ix6JD3+RCLYES27lgiVWs71RVHhOWJeSU0w4CxR514GFyO/j3+LXgtwprvpb3YuyJN6N3ybdqZhAx7TjExKTa1uLnIC5rPeE9bk3F2jDIzOQjFugi+RaIJLTwoot80v20AxOxnjBtjOJCzb7DjNkjRzk0RO4NTvrh7h894nrjGrqqvWzLAJ03AZfC2IzkhGWyi+4hdjI9xIlmrkT6oyuH0uB89pOy75pYTUhLsRCHf8zMKeu05K6dR0WxIwIdXsK8IY9d0y1SE6qncq3hE7DSnyebRBmL4e2Bh0QVvLTCJ7dv8o4wUMJ+6E+KgQR3Maw5lWbJywU1kB0XUhNCRpZmkBIxAOQ/1eCOOmZHL+BXicualinaUG6OZl2Ye6nhnsMQhqylhAT87kihqZGlg744QGKMZ+0dJ2JPP+JS7rF6+q11pRbaNavhceJ65gk=
