version: 1
vaults:
    -
        fsPath: vault
        name: dendron.dendron-site
useFMTitle: true
useNoteTitleForLink: true
noAutoCreateOnDefinition: true
noLegacyNoteRef: true
noXVaultWikiLink: true
lookupConfirmVaultOnCreate: false
mermaid: true
useKatex: true

autoFoldFrontmatter: false
dev:
    enableWebUI: true
    enablePreviewV2: true
lookup:
    note:
        selectionType: selectionExtract
journal:
    dailyDomain: daily
    name: journal
    dateFormat: y.MM.dd
    addBehavior: childOfDomain
    firstDayOfWeek: 1
scratch:
    name: scratch
    dateFormat: y.MM.dd.HHmmss
    addBehavior: asOwnDomain
site:
    siteHierarchies:
        - dendron
        - pkg
        - tags
        - templates
    siteRootDir: docs
    gh_edit_repository: 'https://github.com/dendronhq/dendron-site'
    usePrettyRefs: true
    copyAssets: true
    logo: vault/assets/images/logo.png
    siteUrl: 'https://wiki.dendron.so'
    siteLastModified: true
    githubCname: wiki.dendron.so
    title: Dendron
    author: dendronhq
    twitter: dendronhq
    description: >-
        Dendron is a local-first, markdown based, hierarchical note taking tool.
        It is meant to help you create, organize, and collaborate on knowledge
        bases of any size.
    ga_tracking: G-B0JN2HHCNY
usePrettyRefs: true
useTitleForLink: true
initializeRemoteVaults: true
dendronVersion: 0.56.0
